### ISSUE TITLE
The difference with AdaptivePooling in PyTorch

### ISSUE THREAD

**Issue by zhaohui-yang** [yueruchen/sppnet-pytorch#3]
Hi, I wonder what is the difference between your implementation of SPP layer and AdaptativeAvgPool2d or AdaptativeMaxPool2d in PyTorch lib? Doc: [AdaptativeAvgPool2d](https://pytorch.org/docs/master/nn.html#torch.nn.AdaptiveAvgPool2d)

Standard AdaptiveAvgPool2d receives pooled size as input and accept any size feature maps, I think this is an implementation of SPP layer.

So, what is the difference between your implementation and those standard functions?

**Comment by yifanjiang19** [comment]
There is no overlap in sppnet procedure, but in adaptativeavgpool2d I guess it isn't.
And sppnet uses maxpool instead of avgpool.

**Comment by zhaohui-yang** [comment]
Thanks a lot.
[AdaptativeMaxPool2d](https://github.com/pytorch/pytorch/blob/a08119afc27f44ff488cbf18c11659d255f378a8/aten/src/THNN/generic/SpatialAdaptiveMaxPooling.c#L5) has maximum width or height overlap of 1 pixel. I think this might be the difference.
